export const Books = [
  {
    title: "Libro 1",
    image: "https://cf.bstatic.com/xdata/images/city/600x600/653311.jpg?k=d78e4c2c0ab5396e367738ae6bd50b61bbf49eaee72fd4641dc514378cba77a6&o=",
    author: "Autor 1",
    price: 2500,
    availability: 20,
  },
  {
    title: "Libro 2",
    image: "https://example.com/libro2.jpg",
    author: "Autor 2",
    price: 20,
    availability: 5,
  },
  {
    title: "Libro 3",
    image: "https://example.com/libro3.jpg",
    author: "Autor 3",
    price: 15,
    availability: 10,
  },
  {
    title: "Libro 4",
    image: "https://example.com/libro4.jpg",
    author: "Autor 4",
    price: 30,
    availability: 12,
  },
  {
    title: "Libro 5",
    image: "https://example.com/libro5.jpg",
    author: "Autor 5",
    price: 10,
    availability: 8,
  },
  {
    title: "Libro 6",
    image: "https://example.com/libro6.jpg",
    author: "Autor 6",
    price: 40,
    availability: 15,
  },
  {
    title: "Libro 7",
    image: "https://example.com/libro7.jpg",
    author: "Autor 7",
    price: 25,
    availability: 7,
  },
  {
    title: "Libro 8",
    image: "https://example.com/libro8.jpg",
    author: "Autor 8",
    price: 18,
    availability: 9,
  },
];
